var fs = require('fs')
var uglify = require('uglify-js')
var path = require('path')

var header = '<!--\nThis file was generated by \'make-readme.js\', edit README.tmpl.md and run \'make build\' instead\n-->'
var contents = fs.readFileSync(path.resolve(__dirname, 'README.tmpl.md'), 'utf8')
var minifyResult = uglify.minify(path.resolve(__dirname, 'uv-api.js'))
contents = contents.replace(/\${minified_js}/, minifyResult.code)
contents = header + '\n' + contents

fs.writeFileSync(path.resolve(__dirname, 'README.md'), contents, 'utf8')

console.log('Written to README.md')
