const fs = require('fs')
const uglify = require('uglify-js')
const path = require('path')

const header = `<!--
  This file was generated by \'make-readme.js\', edit README.tmpl.md and run \'make build\' instead
-->`

const minifyResult = uglify.minify(path.resolve(__dirname, 'uv-api.js'))
let contents = fs.readFileSync(path.resolve(__dirname, 'README.tmpl.md'), 'utf8')
contents = contents.replace(/\${minified_js}/, minifyResult.code)
contents = header + '\n' + contents

fs.writeFileSync(path.resolve(__dirname, 'README.md'), contents, 'utf8')

console.log('Written to README.md')
